# Generated by Django 4.2.20 on 2025-03-23 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0002_remove_post_user_alter_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='description',
            new_name='caption',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
